### ISSUE TITLE
 [ERROR] transport_jni::JNI_RecvTransport_Consume() | Failed to set remote offer sdp: Duplicate a=mid value '2'.

### ISSUE THREAD

**Issue by HuskarHuang** [haiyangwu/mediasoup-demo-android#14]
if two android devices connect,  it will crash here:

mediasoupclient-jni: [ERROR] transport_jni::JNI_RecvTransport_Consume() | Failed to set remote offer sdp: Duplicate a=mid value '2'.
2020-06-17 15:32:27.633 10709-10819/org.mediasoup.droid.demo W/System.err: org.mediasoup.droid.MediasoupException: Failed to set remote offer sdp: Duplicate a=mid value '2'.
2020-06-17 15:32:27.634 10709-10819/org.mediasoup.droid.demo W/System.err:     at org.mediasoup.droid.RecvTransport.nativeConsume(Native Method)
2020-06-17 15:32:27.634 10709-10819/org.mediasoup.droid.demo W/System.err:     at org.mediasoup.droid.RecvTransport.consume(RecvTransport.java:48)
2020-06-17 15:32:27.635 10709-10819/org.mediasoup.droid.demo W/System.err:     at org.mediasoup.droid.lib.RoomClient.onNewConsumer(RoomClient.java:1052)
2020-06-17 15:32:27.635 10709-10819/org.mediasoup.droid.demo W/System.err:     at org.mediasoup.droid.lib.RoomClient.access$300(RoomClient.java:38)
2020-06-17 15:32:27.635 10709-10819/org.mediasoup.droid.demo W/System.err:     at org.mediasoup.droid.lib.RoomClient$2.lambda$onRequest$2$RoomClient$2(RoomClient.java:596)
2020-06-17 15:32:27.635 10709-10819/org.mediasoup.droid.demo W/System.err:     at org.mediasoup.droid.lib.-$$Lambda$RoomClient$2$8B9dCuDRW2LL5UzQlkr80_pqLG0.run(Unknown Source:6)
2020-06-17 15:32:27.635 10709-10819/org.mediasoup.droid.demo W/System.err:     at android.os.Handler.handleCallback(Handler.java:873)
2020-06-17 15:32:27.635 10709-10819/org.mediasoup.droid.demo W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
2020-06-17 15:32:27.635 10709-10819/org.mediasoup.droid.demo W/System.err:     at android.os.Looper.loop(Looper.java:224)
2020-06-17 15:32:27.635 10709-10819/org.mediasoup.droid.demo W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:65)
2020-06-17 15:32:27.635 10709-10819/org.mediasoup.droid.demo E/RoomClient: "newConsumer" request failed:
2020-06-17 15:32:27.635 10709-10819/org.mediasoup.droid.demo E/RoomClient: org.mediasoup.droid.MediasoupException: Failed to set remote offer sdp: Duplicate a=mid value '2'.
2020-06-17 15:32:27.637 10709-10819/org.mediasoup.droid.demo E/RoomClient: org.mediasoup.droid.MediasoupException: Failed to set remote offer sdp: Duplicate a=mid value '2'.

**Comment by haiyangwu** [comment]
dup https://github.com/haiyangwu/mediasoup-client-android/issues/23
