### ISSUE TITLE
Application getting crash when more then 40 users join a room: Failed to create EGL context: 0x3003

### ISSUE THREAD

**Issue by pintukumarpatil** [haiyangwu/mediasoup-demo-android#16]
2020-06-26 17:09:38.442 1107-1107/org.mediasoup.droid.demo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mediasoup.droid.demo, PID: 1107
    android.view.InflateException: Binary XML file line #3: Binary XML file line #3: Error inflating class <unknown>
    Caused by: android.view.InflateException: Binary XML file line #3: Error inflating class <unknown>
    Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:651)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:794)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:734)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:496)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
        at org.mediasoup.droid.demo.adapter.PeerAdapter.onCreateViewHolder(PeerAdapter.java:55)
        at org.mediasoup.droid.demo.adapter.PeerAdapter.onCreateViewHolder(PeerAdapter.java:24)
        at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6794)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5975)
        at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:286)
        at androidx.recyclerview.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:343)
        at androidx.recyclerview.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:359)
        at androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:366)
        at androidx.recyclerview.widget.GapWorker.run(GapWorker.java:397)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6810)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
     Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Failed to create EGL context: 0x3003
        at org.webrtc.EglBase14Impl.createEglContext(EglBase14Impl.java:280)
        at org.webrtc.EglBase14Impl.<init>(EglBase14Impl.java:78)
        at org.webrtc.EglBase$-CC.createEgl14(EglBase.java:215)
        at org.webrtc.EglBase$-CC.create(EglBase.java:158)
        at org.webrtc.EglRenderer.lambda$init$0$EglRenderer(EglRenderer.java:241)
        at org.webrtc.-$$Lambda$EglRenderer$A5MPsBufyTiKpmjvPS46Dr9iaHs.run(Unknown Source:6)
        at org.webrtc.ThreadUtils$4.call(ThreadUtils.java:199)
        at org.webrtc.ThreadUtils$4.call(ThreadUtils.java:196)
        at org.webrtc.ThreadUtils$3.run(ThreadUtils.java:173)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at org.webrtc.EglRenderer$HandlerWithExceptionCallback.dispatchMessage(EglRenderer.java:103)
        at android.os.Looper.loop(Looper.java:201)
        at android.os.HandlerThread.run(HandlerThread.java:65)
        at org.webrtc.ThreadUtils.invokeAtFrontUninterruptibly(ThreadUtils.java:184)
        at org.webrtc.ThreadUtils.invokeAtFrontUninterruptibly(ThreadUtils.java:196)
        at org.webrtc.EglRenderer.init(EglRenderer.java:232)
        at org.webrtc.EglRenderer.init(EglRenderer.java:259)
        at org.webrtc.SurfaceEglRenderer.init(SurfaceEglRenderer.java:61)
        at org.webrtc.SurfaceViewRenderer.init(SurfaceViewRenderer.java:87)
        at org.webrtc.SurfaceViewRenderer.init(SurfaceViewRenderer.java:71)
        at org.mediasoup.droid.demo.view.PeerView.init(PeerView.java:51)
        at org.mediasoup.droid.demo.view.PeerView.<init>(PeerView.java:33)
        at java.lang.reflect.Constructor.newInstance0(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:651) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:794) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:734) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:496) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:427) 
        at org.mediasoup.droid.demo.adapter.PeerAdapter.onCreateViewHolder(PeerAdapter.java:55) 
        at org.mediasoup.droid.demo.adapter.PeerAdapter.onCreateViewHolder(PeerAdapter.java:24) 
        at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6794) 
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5975) 
        at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:286) 
        at androidx.recyclerview.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:343) 
        at androidx.recyclerview.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:359) 
        at androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:366) 
        at androidx.recyclerview.widget.GapWorker.run(GapWorker.java:397) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:201) 
        at android.app.ActivityThread.main(ActivityThread.java:6810) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873) 
     Caused by: java.lang.RuntimeException: Failed to create EGL context: 0x3003
        at org.webrtc.EglBase14Impl.createEglContext(EglBase14Impl.java:280)
        at org.webrtc.EglBase14Impl.<init>(EglBase14Impl.java:78)
        at org.webrtc.EglBase$-CC.createEgl14(EglBase.java:215)
        at org.webrtc.EglBase$-CC.create(EglBase.java:158)
        at org.webrtc.EglRenderer.lambda$init$0$EglRenderer(EglRenderer.java:241)
2020-06-26 17:09:38.442 1107-1107/org.mediasoup.droid.demo E/AndroidRuntime:     at org.webrtc.-$$Lambda$EglRenderer$A5MPsBufyTiKpmjvPS46Dr9iaHs.run(Unknown Source:6)
        at org.webrtc.ThreadUtils$4.call(ThreadUtils.java:199)
        at org.webrtc.ThreadUtils$4.call(ThreadUtils.java:196)
        at org.webrtc.ThreadUtils$3.run(ThreadUtils.java:173)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at org.webrtc.EglRenderer$HandlerWithExceptionCallback.dispatchMessage(EglRenderer.java:103)
        at android.os.Looper.loop(Looper.java:201)
        at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by haiyangwu** [comment]
This is just a demo, if used in your project,  pls try to refine the impl of `Video Render Management`.
