### ISSUE TITLE
 Sometime facing issue: No implementation found for void org.webrtc.voiceengine.WebRtcAudioTrack.nativeGetPlayoutData

### ISSUE THREAD

**Issue by pintukumarpatil** [haiyangwu/mediasoup-demo-android#17]
Sometime facing issue:
org.mediasoup.droid.demo E/soup.droid.dem: No implementation found for void org.webrtc.voiceengine.WebRtcAudioTrack.nativeGetPlayoutData(int, long) (tried Java_org_webrtc_voiceengine_WebRtcAudioTrack_nativeGetPlayoutData and Java_org_webrtc_voiceengine_WebRtcAudioTrack_nativeGetPlayoutData__IJ)
2020-07-08 15:31:16.473 11162-12312/org.mediasoup.droid.demo E/AndroidRuntime: FATAL EXCEPTION: AudioTrackJavaThread
    Process: org.mediasoup.droid.demo, PID: 11162
    java.lang.UnsatisfiedLinkError: No implementation found for void org.webrtc.voiceengine.WebRtcAudioTrack.nativeGetPlayoutData(int, long) (tried Java_org_webrtc_voiceengine_WebRtcAudioTrack_nativeGetPlayoutData and Java_org_webrtc_voiceengine_WebRtcAudioTrack_nativeGetPlayoutData__IJ)
        at org.webrtc.voiceengine.WebRtcAudioTrack.nativeGetPlayoutData(Native Method)
        at org.webrtc.voiceengine.WebRtcAudioTrack.access$400(WebRtcAudioTrack.java:28)
        at org.webrtc.voiceengine.WebRtcAudioTrack$AudioTrackThread.run(WebRtcAudioTrack.java:147)

**Comment by Ben0421** [comment]
This looks pretty similar to [https://github.com/haiyangwu/mediasoup-client-android/issues/12](https://github.com/haiyangwu/mediasoup-client-android/issues/12).
